/**
 * Language Context
 * Provides English/French language switching
 */
import { createContext, useContext, useEffect, useState, ReactNode } from 'react'

export type Language = 'en' | 'fr'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

const LANGUAGE_STORAGE_KEY = 'lameness-language'

// Translation dictionary
const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.cowRegistry': 'Cow Registry',
    'nav.pairwise': 'Pairwise',
    'nav.pairwiseTutorial': 'Pairwise Tutorial',
    'nav.performance': 'Performance',
    'nav.pairResults': 'Pair Results',
    'dashboard.overview': 'Overview of your lameness detection research pipeline',
    'dashboard.pairwiseProgress': 'Pairwise Comparisons',
    'dashboard.humanAnnotation': 'Human annotation progress',
    'dashboard.continueComparing': 'Continue Comparing',
    'dashboard.uploadToStart': 'Upload at least 2 videos to start pairwise comparisons',
    'dashboard.mostLame': 'Most Lame',
    'dashboard.top5': 'Top 5 by pairwise consensus',
    'dashboard.viewFullRegistry': 'View Full Registry',
    'dashboard.cowRanking': 'Cow Lameness Ranking',
    'dashboard.recentVideos': 'Recent Videos',
    'dashboard.showing': 'Showing',
    'dashboard.of': 'of',
    'dashboard.cows': 'cows',
    'dashboard.videos': 'videos',
    'dashboard.noVideos': 'No videos yet',
    'dashboard.uploadToStartJourney': 'Upload cow walking videos to start your lameness analysis journey',
    'dashboard.uploadVideos': 'Upload Videos',
    'dashboard.rank': 'Rank',
    'dashboard.cow': 'Cow',
    'dashboard.status': 'Status',
    'dashboard.eloScore': 'Elo Score',
    'dashboard.label': 'Label',
    'dashboard.size': 'Size',
    'dashboard.actions': 'Actions',
    'dashboard.annotated': 'Annotated',
    'dashboard.analyzed': 'Analyzed',
    'dashboard.pending': 'Pending',
    'dashboard.sound': 'Sound',
    'dashboard.lame': 'Lame',
    'dashboard.unlabeled': 'Unlabeled',
    'dashboard.view': 'View',
    'dashboard.results': 'Results',
    'dashboard.noVideoAvailable': 'No video available',
    'dashboard.clickResults': 'Click Results to see pairwise comparison history, or View to open the full detail page.',
    'nav.triplet': 'Triplet',
    'nav.hierarchy': 'Hierarchy',
    'nav.similarity': 'Similarity',
    'nav.learn': 'Learn',
    
    // Pairwise Comparison
    'pairwise.tasksTitle': 'Pairwise Comparison Tasks',
    'pairwise.tasksSubtitle': 'Select a task to start comparing cow walking videos. Each task contains a set of video pairs from the same farm session.',
    'pairwise.notSure': 'Not sure how to do it?',
    'pairwise.clickTutorial': 'Click Tutorial',
    'pairwise.redoTask': 'Redo Task',
    'pairwise.startTaskArrow': 'Start Task →',
    'pairwise.completed': 'Completed',
    'pairwise.pairs': 'pairs',
    'pairwise.ratersCompleted': 'raters completed',
    'pairwise.completion': 'Completion',
    'pairwise.taskComplete': 'Task Complete!',
    'pairwise.finishedAll': 'You\'ve finished all',
    'pairwise.comparisonsFor': 'comparisons for',
    'pairwise.comparisons': 'comparisons',
    'pairwise.returnToMainPage': 'Return to main page',
    'pairwise.title': 'Pairwise Comparison',
    'pairwise.subtitle': 'Compare videos using a 7-point scale to build a lameness hierarchy',
    'pairwise.leftCow': 'Left Cow',
    'pairwise.rightCow': 'Right Cow',
    'pairwise.play': 'Play',
    'pairwise.pause': 'Pause',
    'pairwise.restart': 'Restart',
    'pairwise.selectOption': 'Select the option that best describes the lameness difference',
    'pairwise.leftMoreLame': 'Left more lame',
    'pairwise.rightMoreLame': 'Right more lame',
    'pairwise.submit': 'Submit & Next Pair (Enter)',
    'pairwise.submitting': 'Submitting...',
    'pairwise.showRanking': 'Show Ranking',
    'pairwise.share': 'Share',
    'pairwise.retakeTutorial': 'Retake Tutorial',
    'pairwise.skipTutorial': 'Skip Tutorial',
    'pairwise.loading': 'Loading video pair...',
    'pairwise.allComplete': 'All Comparisons Complete!',
    'pairwise.allCompleteMsg': "You've completed all pairwise comparisons. Great work!",
    'pairwise.goToDashboard': 'Go to Dashboard',
    
    // Tutorial
    'tutorial.title': 'Pairwise Comparison Tutorial',
    'tutorial.subtitle': '5 high-contrast examples from consensus results. Feedback appears immediately when you select a score.',
    'tutorial.step': 'Step',
    'tutorial.of': 'of',
    'tutorial.correct': 'Correct!',
    'tutorial.notQuite': 'Not quite right',
    'tutorial.checkAnswer': 'Check Answer',
    'tutorial.nextExample': 'Next Example',
    'tutorial.startReal': 'Start Real Comparisons',
    'tutorial.score': 'Score:',
    'tutorial.whatToLookFor': 'What to Look For:',
    'tutorial.archedBack': 'Arched Back',
    'tutorial.archedBackDesc': 'Hunched posture while walking',
    'tutorial.headBobbing': 'Head Bobbing',
    'tutorial.headBobbingDesc': 'Up/down head movement',
    'tutorial.unevenStride': 'Uneven Stride',
    'tutorial.unevenStrideDesc': 'Favoring one leg',
    'tutorial.slowMovement': 'Slow Movement',
    'tutorial.slowMovementDesc': 'Hesitant or cautious gait',
    'tutorial.finish': 'Finish Tutorial',
    'tutorial.nextPair': 'Next Pair',
    'tutorial.answered': 'Answered:',
    'tutorial.selectLameness': 'Select lameness difference',
    'tutorial.feedbackGreat': 'You\'re very close to what everyone else believes!',
    'tutorial.feedbackGood': 'Your take aligns with the majority on this pair!',
    'tutorial.feedbackInterestingAgree': 'You agree on which cow is lamer, but see the degree a bit differently.',
    'tutorial.feedbackInterestingDisagree': 'Interesting perspective! Many raters actually saw this the other way.',
    'tutorial.feedbackUnique': 'Oops... this is quite a unique point of view!',
    'tutorial.crowdCenter': 'Crowd center:',
    'tutorial.yourDistance': 'Your distance:',
    'tutorial.votes': 'votes',
    'tutorial.yourAnswer': 'Your answer',
    
    // Pair Results
    'pairResults.title': 'Pair Results',
    'pairResults.subtitle': 'Consensus data and score distributions for all pairwise comparisons',
    'pairResults.totalPairs': 'Total Pairs',
    'pairResults.totalJudgments': 'Total Judgments',
    'pairResults.avgAgreement': 'Avg. Agreement',
    'pairResults.searchPlaceholder': 'Search by Cow ID...',
    'pairResults.sortAgreementDesc': 'Highest Agreement',
    'pairResults.sortAgreementAsc': 'Lowest Agreement',
    'pairResults.sortJudgmentsDesc': 'Most Judgments',
    'pairResults.sortJudgmentsAsc': 'Fewest Judgments',
    'pairResults.sortVarianceDesc': 'Highest Variance',
    'pairResults.sortVarianceAsc': 'Lowest Variance',
    'pairResults.cow': 'Cow',
    'pairResults.vs': 'vs',
    'pairResults.judgments': 'judgments',
    'pairResults.agreement': 'agreement',
    'pairResults.meanScore': 'Mean Score',
    'pairResults.variance': 'Variance',
    'pairResults.leftMoreLame': 'Left more lame',
    'pairResults.rightMoreLame': 'Right more lame',
    'pairResults.equal': 'Equal',
    'pairResults.playVideo': 'Play video',
    'pairResults.pauseVideo': 'Pause video',
    'pairResults.score': 'Score',
    'pairResults.votes': 'votes',
    'pairResults.consensus': 'Consensus',
    'performance.title': 'Your Rating Performance',
    'performance.subtitle': 'See how well your ratings match with other raters',
    'performance.totalCompleted': 'Total Ratings Completed',
    'performance.totalCompletedDesc': 'Number of cow comparisons you\'ve rated',
    'performance.agreementScore': 'Agreement Score',
    'performance.agreementScoreDesc': 'How often your ratings match other raters',
    'performance.topPercent': 'You\'re in the Top',
    'performance.rateMoreAccurately': 'You rate more accurately than',
    'performance.outOf100': 'out of 100 raters',
    'performance.youAreHere': 'You are here',
    'performance.whatThisMeans': 'What This Means',
    'performance.doingGreat': 'You\'re Doing Great!',
    'performance.doingGreatDesc': 'Your ratings are very consistent and match well with other experienced raters. Keep up the good work!',
    'performance.highAgreement': 'High Agreement Rate',
    'performance.highAgreementDesc1': '',
    'performance.highAgreementDesc2': '% of your ratings match the consensus. This shows you can reliably identify lameness in cows.',
    'performance.keepRating': 'Keep Rating',
    'performance.keepRatingDesc': 'The more comparisons you complete, the more accurate the system becomes at detecting lameness patterns.',
    'pairResults.noPairsMatch': 'No pairs match your search.',
    
    // Triplet
    'triplet.title': 'Triplet Comparison',
    'triplet.subtitle': 'Help train our AI by identifying which cow is more similar to the reference',
    'triplet.reference': 'Reference Cow',
    'triplet.whichMoreSimilar': 'Which cow is more similar to the reference?',
    'triplet.comparisonA': 'Cow A',
    'triplet.comparisonB': 'Cow B',
    'triplet.confidence': 'Confidence',
    'triplet.high': 'High',
    'triplet.medium': 'Medium',
    'triplet.low': 'Low',
    'triplet.allComplete': 'All Triplet Tasks Complete!',
    'triplet.allCompleteMsg': "You've completed all triplet comparisons. Great work!",
    'triplet.goToPairwise': 'Go to Pairwise Comparison',
    
    // Performance
    'performance.totalRatings': 'Total Ratings',
    'performance.accuracy': 'Accuracy',
    'performance.meanDeviation': 'Mean Deviation',
    'performance.consistency': 'Consistency',
    'performance.distributionTitle': 'Your Performance Distribution',
    'performance.distributionDesc': 'Your ratings compared to the majority consensus. You are within',
    'performance.distributionDescEnd': 'standard deviations from the mean.',
    'performance.you': 'YOU',
    'performance.otherRaters': 'Other raters',
    'performance.yourPosition': 'Your position',
    'performance.sigmaNote': 'σ (sigma) represents standard deviation from the mean (μ)',
    'performance.insightsTitle': 'Performance Insights',
    'performance.goodConsistency': 'Good Consistency',
    'performance.consistencyDesc': 'Your ratings are closely aligned with expert consensus (within',
    'performance.aboveAverage': 'Above Average Performance',
    'performance.aboveAverageDesc': "You're performing better than",
    'performance.aboveAverageDescEnd': 'of raters',
    
    // Common
    'common.progress': 'Progress:',
    'common.pairs': 'pairs',
    'common.tasks': 'tasks',
    'common.loading': 'Loading...',
    'common.settings': 'Settings',
    'common.logout': 'Logout',
    'common.search': 'Search...',
    'common.quickLinks': 'Quick Links',
  },
  fr: {
    // Navigation
    'nav.dashboard': 'Tableau de bord',
    'nav.cowRegistry': 'Registre des vaches',
    'nav.pairwise': 'Comparaison par paires',
    'nav.pairwiseTutorial': 'Tutoriel par paires',
    'nav.performance': 'Performance',
    'nav.pairResults': 'Résultats des paires',
    'dashboard.overview': 'Aperçu de votre pipeline de recherche sur la détection des boiteries',
    'dashboard.pairwiseProgress': 'Comparaisons par paires',
    'dashboard.humanAnnotation': 'Progression de l\'annotation humaine',
    'dashboard.continueComparing': 'Continuer à comparer',
    'dashboard.uploadToStart': 'Téléchargez au moins 2 vidéos pour commencer les comparaisons par paires',
    'dashboard.mostLame': 'Les plus boiteuses',
    'dashboard.top5': 'Top 5 selon le consensus des paires',
    'dashboard.viewFullRegistry': 'Voir le registre complet',
    'dashboard.cowRanking': 'Classement des boiteries des vaches',
    'dashboard.recentVideos': 'Vidéos récentes',
    'dashboard.showing': 'Affichage de',
    'dashboard.of': 'sur',
    'dashboard.cows': 'vaches',
    'dashboard.videos': 'vidéos',
    'dashboard.noVideos': 'Aucune vidéo pour le moment',
    'dashboard.uploadToStartJourney': 'Téléchargez des vidéos de vaches qui marchent pour commencer',
    'dashboard.uploadVideos': 'Télécharger des vidéos',
    'dashboard.rank': 'Rang',
    'dashboard.cow': 'Vache',
    'dashboard.status': 'Statut',
    'dashboard.eloScore': 'Score Elo',
    'dashboard.label': 'Étiquette',
    'dashboard.size': 'Taille',
    'dashboard.actions': 'Actions',
    'dashboard.annotated': 'Annoté',
    'dashboard.analyzed': 'Analysé',
    'dashboard.pending': 'En attente',
    'dashboard.sound': 'Saine',
    'dashboard.lame': 'Boiteuse',
    'dashboard.unlabeled': 'Non étiqueté',
    'dashboard.view': 'Voir',
    'dashboard.results': 'Résultats',
    'dashboard.noVideoAvailable': 'Aucune vidéo disponible',
    'dashboard.clickResults': 'Cliquez sur Résultats pour voir l\'historique des comparaisons, ou Voir pour ouvrir la page détaillée.',
    'nav.triplet': 'Triplet',
    'nav.hierarchy': 'Hiérarchie',
    'nav.similarity': 'Similarité',
    'nav.learn': 'Apprendre',
    
    // Pairwise Comparison
    'pairwise.tasksTitle': 'Tâches de comparaison par paires',
    'pairwise.tasksSubtitle': 'Sélectionnez une tâche pour commencer à comparer les vidéos de marche des vaches. Chaque tâche contient un ensemble de paires de vidéos de la même session à la ferme.',
    'pairwise.notSure': 'Vous ne savez pas comment faire ?',
    'pairwise.clickTutorial': 'Cliquez sur Tutoriel',
    'pairwise.redoTask': 'Refaire la tâche',
    'pairwise.startTaskArrow': 'Commencer la tâche →',
    'pairwise.completed': 'Terminé',
    'pairwise.pairs': 'paires',
    'pairwise.ratersCompleted': 'évaluateurs ont terminé',
    'pairwise.completion': 'Achèvement',
    'pairwise.taskComplete': 'Tâche terminée !',
    'pairwise.finishedAll': 'Vous avez terminé toutes les',
    'pairwise.comparisonsFor': 'comparaisons pour',
    'pairwise.comparisons': 'comparaisons',
    'pairwise.returnToMainPage': 'Retour à la page principale',
    'pairwise.title': 'Comparaison par paires',
    'pairwise.subtitle': 'Comparez les vidéos à l\'aide d\'une échelle de 7 points pour construire une hiérarchie de boiterie',
    'pairwise.leftCow': 'Vache gauche',
    'pairwise.rightCow': 'Vache droite',
    'pairwise.play': 'Lecture',
    'pairwise.pause': 'Pause',
    'pairwise.restart': 'Redémarrer',
    'pairwise.selectOption': 'Sélectionnez l\'option qui décrit le mieux la différence de boiterie',
    'pairwise.leftMoreLame': 'Gauche plus boiteuse',
    'pairwise.rightMoreLame': 'Droite plus boiteuse',
    'pairwise.submit': 'Soumettre et paire suivante (Entrée)',
    'pairwise.submitting': 'Envoi...',
    'pairwise.showRanking': 'Afficher le classement',
    'pairwise.share': 'Partager',
    'pairwise.retakeTutorial': 'Refaire le tutoriel',
    'pairwise.skipTutorial': 'Passer le tutoriel',
    'pairwise.loading': 'Chargement de la paire de vidéos...',
    'pairwise.allComplete': 'Toutes les comparaisons terminées!',
    'pairwise.allCompleteMsg': 'Vous avez terminé toutes les comparaisons par paires. Excellent travail!',
    'pairwise.goToDashboard': 'Aller au tableau de bord',
    
    // Tutorial
    'tutorial.title': 'Tutoriel de comparaison par paires',
    'tutorial.subtitle': '5 exemples contrastés tirés des résultats du consensus. Les commentaires apparaissent immédiatement lorsque vous sélectionnez un score.',
    'tutorial.step': 'Étape',
    'tutorial.of': 'sur',
    'tutorial.correct': 'Correct!',
    'tutorial.notQuite': 'Pas tout à fait',
    'tutorial.checkAnswer': 'Vérifier la réponse',
    'tutorial.nextExample': 'Exemple suivant',
    'tutorial.startReal': 'Commencer les vraies comparaisons',
    'tutorial.score': 'Score:',
    'tutorial.whatToLookFor': 'Ce qu\'il faut observer:',
    'tutorial.archedBack': 'Dos voûté',
    'tutorial.archedBackDesc': 'Posture voûtée en marchant',
    'tutorial.headBobbing': 'Hochement de tête',
    'tutorial.headBobbingDesc': 'Mouvement de la tête de haut en bas',
    'tutorial.unevenStride': 'Foulée inégale',
    'tutorial.unevenStrideDesc': 'Favorise une patte',
    'tutorial.slowMovement': 'Mouvement lent',
    'tutorial.slowMovementDesc': 'Démarche hésitante ou prudente',
    'tutorial.finish': 'Terminer le tutoriel',
    'tutorial.nextPair': 'Paire suivante',
    'tutorial.answered': 'Répondu:',
    'tutorial.selectLameness': 'Sélectionnez la différence de boiterie',
    'tutorial.feedbackGreat': 'Vous êtes très proche de ce que tout le monde pense!',
    'tutorial.feedbackGood': 'Votre avis correspond à la majorité pour cette paire!',
    'tutorial.feedbackInterestingAgree': 'Vous êtes d\'accord sur quelle vache est la plus boiteuse, mais voyez le degré un peu différemment.',
    'tutorial.feedbackInterestingDisagree': 'Perspective intéressante! Beaucoup d\'évaluateurs ont vu les choses autrement.',
    'tutorial.feedbackUnique': 'Oups... c\'est un point de vue assez unique!',
    'tutorial.crowdCenter': 'Centre du groupe:',
    'tutorial.yourDistance': 'Votre distance:',
    'tutorial.votes': 'votes',
    'tutorial.yourAnswer': 'Votre réponse',
    
    // Pair Results
    'pairResults.title': 'Résultats des paires',
    'pairResults.subtitle': 'Données de consensus et distributions des scores pour toutes les comparaisons par paires',
    'pairResults.totalPairs': 'Total des paires',
    'pairResults.totalJudgments': 'Jugements totaux',
    'pairResults.avgAgreement': 'Accord moyen',
    'pairResults.searchPlaceholder': 'Rechercher par ID de vache...',
    'pairResults.sortAgreementDesc': 'Accord le plus élevé',
    'pairResults.sortAgreementAsc': 'Accord le plus bas',
    'pairResults.sortJudgmentsDesc': 'Plus de jugements',
    'pairResults.sortJudgmentsAsc': 'Moins de jugements',
    'pairResults.sortVarianceDesc': 'Variance la plus élevée',
    'pairResults.sortVarianceAsc': 'Variance la plus basse',
    'pairResults.cow': 'Vache',
    'pairResults.vs': 'vs',
    'pairResults.judgments': 'jugements',
    'pairResults.agreement': 'accord',
    'pairResults.meanScore': 'Score moyen',
    'pairResults.variance': 'Variance',
    'pairResults.leftMoreLame': 'Gauche plus boiteuse',
    'pairResults.rightMoreLame': 'Droite plus boiteuse',
    'pairResults.equal': 'Égale',
    'pairResults.playVideo': 'Lire la vidéo',
    'pairResults.pauseVideo': 'Mettre en pause',
    'pairResults.score': 'Score',
    'pairResults.votes': 'votes',
    'pairResults.consensus': 'Consensus',
    'performance.title': 'Vos performances d\'évaluation',
    'performance.subtitle': 'Voyez comment vos évaluations correspondent à celles des autres évaluateurs',
    'performance.totalCompleted': 'Total des évaluations terminées',
    'performance.totalCompletedDesc': 'Nombre de comparaisons de vaches que vous avez évaluées',
    'performance.agreementScore': 'Score de concordance',
    'performance.agreementScoreDesc': 'À quelle fréquence vos évaluations correspondent aux autres',
    'performance.topPercent': 'Vous êtes dans le Top',
    'performance.rateMoreAccurately': 'Vous évaluez avec plus de précision que',
    'performance.outOf100': 'sur 100 évaluateurs',
    'performance.youAreHere': 'Vous êtes ici',
    'performance.whatThisMeans': 'Ce que cela signifie',
    'performance.doingGreat': 'Vous faites du bon travail !',
    'performance.doingGreatDesc': 'Vos évaluations sont très cohérentes et correspondent bien aux autres évaluateurs expérimentés. Continuez comme ça !',
    'performance.highAgreement': 'Taux de concordance élevé',
    'performance.highAgreementDesc1': '',
    'performance.highAgreementDesc2': '% de vos évaluations correspondent au consensus. Cela montre que vous pouvez identifier de manière fiable la boiterie chez les vaches.',
    'performance.keepRating': 'Continuez à évaluer',
    'performance.keepRatingDesc': 'Plus vous effectuez de comparaisons, plus le système devient précis pour détecter les modèles de boiterie.',
    'pairResults.split': 'Partagé',
    'pairResults.noPairsMatch': 'Aucune paire ne correspond à votre recherche.',
    
    // Triplet
    'triplet.title': 'Comparaison en triplet',
    'triplet.subtitle': 'Aidez à former notre IA en identifiant quelle vache est la plus similaire à la référence',
    'triplet.reference': 'Vache de référence',
    'triplet.whichMoreSimilar': 'Quelle vache est la plus similaire à la référence?',
    'triplet.comparisonA': 'Vache A',
    'triplet.comparisonB': 'Vache B',
    'triplet.confidence': 'Confiance',
    'triplet.high': 'Haute',
    'triplet.medium': 'Moyenne',
    'triplet.low': 'Faible',
    'triplet.allComplete': 'Toutes les tâches en triplet terminées!',
    'triplet.allCompleteMsg': 'Vous avez terminé toutes les comparaisons en triplet. Excellent travail!',
    'triplet.goToPairwise': 'Aller à la comparaison par paires',
    
    // Performance
    'performance.totalRatings': 'Évaluations totales',
    'performance.accuracy': 'Précision',
    'performance.meanDeviation': 'Déviation moyenne',
    'performance.consistency': 'Cohérence',
    'performance.distributionTitle': 'Distribution de votre performance',
    'performance.distributionDesc': 'Vos évaluations comparées au consensus majoritaire. Vous êtes à',
    'performance.distributionDescEnd': 'écarts-types de la moyenne.',
    'performance.you': 'VOUS',
    'performance.otherRaters': 'Autres évaluateurs',
    'performance.yourPosition': 'Votre position',
    'performance.sigmaNote': 'σ (sigma) représente l\'écart-type par rapport à la moyenne (μ)',
    'performance.insightsTitle': 'Aperçu des performances',
    'performance.goodConsistency': 'Bonne cohérence',
    'performance.consistencyDesc': 'Vos évaluations sont étroitement alignées sur le consensus d\'experts (à',
    'performance.aboveAverage': 'Performance supérieure à la moyenne',
    'performance.aboveAverageDesc': 'Vous performez mieux que',
    'performance.aboveAverageDescEnd': 'des évaluateurs',
    
    // Common
    'common.progress': 'Progrès:',
    'common.pairs': 'paires',
    'common.tasks': 'tâches',
    'common.loading': 'Chargement...',
    'common.settings': 'Paramètres',
    'common.logout': 'Déconnexion',
    'common.search': 'Rechercher...',
    'common.quickLinks': 'Liens rapides',
  },
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window === 'undefined') return 'en'
    return (localStorage.getItem(LANGUAGE_STORAGE_KEY) as Language) || 'en'
  })

  const setLanguage = (newLanguage: Language) => {
    setLanguageState(newLanguage)
    localStorage.setItem(LANGUAGE_STORAGE_KEY, newLanguage)
  }

  const t = (key: string): string => {
    return translations[language][key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
